name: Build

permissions: read-all

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 3
      matrix:
        pg-version: [10, 11, 12, 13, 14]
    steps:
      - id: install
        run: |
          # Remove preinstalled Postgres because this will conflict with the version we actually want.
          sudo apt-get remove -u postgresql\*
          # Setup the Postgres repositories
          sudo sh -c 'echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          sudo apt-get update
          # Install build deps
          sudo apt-get install -y postgresql-server-dev-${{ matrix.pg-version }}
      - id: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - id: make
        run: make

